version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    working_dir: /app-shopper
    volumes:
      - .:/app-shopper
      - /app-shopper/node_modules
      - db_data:/app-shopper/prisma
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app-shopper/prisma/dev.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: ["npm", "run", "dev"]
    restart: unless-stopped

volumes:
  db_data: